### ISSUE TITLE
Documentation example is not working

### ISSUE THREAD

**Issue by MasterBiryer** [python-turbulette/turbulette#61]
**Describe the bug**
The example is not working: when I follow all the steps (or so I believe...) I get this error:
```
ValueError: Field registerCard is not defined on type Mutation
```

**To Reproduce**
Steps to reproduce the behavior: follow the [quick start guide](https://python-turbulette.github.io/turbulette/)  

**Expected behavior**
I expect no error and to be able to connect to the graphql playground to test the example.

**Environment**
poetry env as defined on the turbulette example under macOS

* [x] **Explain with a simple sentence the expected behavior**
A working example

* [x] **Turbulette version:**
```
(master-njb6Mycc-py3.8) bash-3.2$ poetry show turbulette
name         : turbulette
version      : 0.4.0
description  : A batteries-included framework to build high performance, async GraphQL APIs

dependencies
 - alembic >=1.4.2,<2.0.0
 - ariadne >=0.11,<0.13
 - async-caches >=0.3.0,<0.4.0
 - ciso8601 >=2.1.3,<3.0.0
 - click >=7.1.2,<8.0.0
 - gino >=1.0.1,<2.0.0
 - passlib >=1.7.2,<2.0.0
 - psycopg2 >=2.8.5,<3.0.0
 - pydantic >=1.6.1,<2.0.0
 - python-jwt >=3.2.6,<4.0.0
 - simple-settings >=0.19.1,<1.1.0
```

* [x] **Python version:**
Python 3.8

* [x] **Executed in docker:**
No

* [x] **Dockerfile sample:**
NA

* [x] **GraphQL Schema & Query:** 
```
extend type Mutation {
    registerCard(input: CreditCard!): SuccessOut!
}

input CreditCard {
    number: String!
    expiration: Date!
    name: String!
}

type SuccessOut {
    success: Boolean
    errors: [String]
}

```
* [x] **Is it a regression from a previous versions?**
No

* [x] **Stack trace**
```
(master-njb6Mycc-py3.8) bash-3.2$ uvicorn backend.app:app --port 8000
Traceback (most recent call last):
  File "/Users/master/Library/Caches/pypoetry/virtualenvs/backend-njb6Mycc-py3.8/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/Users/master/Library/Caches/pypoetry/virtualenvs/backend-njb6Mycc-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/master/Library/Caches/pypoetry/virtualenvs/backend-njb6Mycc-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/master/Library/Caches/pypoetry/virtualenvs/backend-njb6Mycc-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/master/Library/Caches/pypoetry/virtualenvs/backend-njb6Mycc-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/master/Library/Caches/pypoetry/virtualenvs/backend-njb6Mycc-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 357, in main
    run(**kwargs)
  File "/Users/master/Library/Caches/pypoetry/virtualenvs/backend-njb6Mycc-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 381, in run
    server.run()
  File "/Users/master/Library/Caches/pypoetry/virtualenvs/backend-njb6Mycc-py3.8/lib/python3.8/site-packages/uvicorn/_impl/asyncio.py", line 47, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/master/Library/Caches/pypoetry/virtualenvs/backend-njb6Mycc-py3.8/lib/python3.8/site-packages/uvicorn/_impl/asyncio.py", line 54, in serve
    config.load()
  File "/Users/master/Library/Caches/pypoetry/virtualenvs/backend-njb6Mycc-py3.8/lib/python3.8/site-packages/uvicorn/config.py", line 306, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/master/Library/Caches/pypoetry/virtualenvs/backend-njb6Mycc-py3.8/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./backend/app.py", line 5, in <module>
    app = turbulette_starlette()
  File "/Users/master/Library/Caches/pypoetry/virtualenvs/backend-njb6Mycc-py3.8/lib/python3.8/site-packages/turbulette/asgi.py", line 106, in turbulette_starlette
    graphql_route = setup(project_settings, is_database)
  File "/Users/master/Library/Caches/pypoetry/virtualenvs/backend-njb6Mycc-py3.8/lib/python3.8/site-packages/turbulette/main.py", line 41, in setup
    schema = registry.setup()
  File "/Users/master/Library/Caches/pypoetry/virtualenvs/backend-njb6Mycc-py3.8/lib/python3.8/site-packages/turbulette/apps/registry.py", line 150, in setup
    executable_schema = make_schema(
  File "/Users/master/Library/Caches/pypoetry/virtualenvs/backend-njb6Mycc-py3.8/lib/python3.8/site-packages/ariadne/executable_schema.py", line 35, in make_executable_schema
    bindable.bind_to_schema(schema)
  File "/Users/master/Library/Caches/pypoetry/virtualenvs/backend-njb6Mycc-py3.8/lib/python3.8/site-packages/ariadne/objects.py", line 41, in bind_to_schema
    self.bind_resolvers_to_graphql_type(graphql_type)
  File "/Users/master/Library/Caches/pypoetry/virtualenvs/backend-njb6Mycc-py3.8/lib/python3.8/site-packages/ariadne/objects.py", line 55, in bind_resolvers_to_graphql_type
    raise ValueError(
ValueError: Field registerCard is not defined on type Mutation

```

* [x] **Other**
Additionnaly, `mypy` whines on this line:
```
from ..pyd_models import CreditCard

-> Relative import climbs too many namespaces mypy(error)

```

**Comment by gazorby** [comment]
Hi @MasterBiryer , thanks for trying out Turbulette!

I just reproduced this error and it seems that there is an error in the docs as Ariadne only support `.graphql` extension AFAIK.

So you should just have to change the file extension to `.graphql`.

I'm working on the docs to cover all aspects of the framework (user guides + reference), it'll be available soon ;)

**Comment by MasterBiryer** [comment]
Ah yes, now works. Quick fix... 😄 

Thank you.

**Comment by MasterBiryer** [comment]
> I'm working on the docs to cover all aspects of the framework (user guides + reference), it'll be available soon ;)

I can't wait...

Thank you.
